[2022-04-22 10:19:02,652] {processor.py:163} INFO - Started process (PID=14464) to work on /opt/airflow/dags/simple_dag.py
[2022-04-22 10:19:02,653] {processor.py:642} INFO - Processing file /opt/airflow/dags/simple_dag.py for tasks to queue
[2022-04-22 10:19:02,654] {logging_mixin.py:109} INFO - [2022-04-22 10:19:02,654] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/simple_dag.py
[2022-04-22 10:19:02,663] {logging_mixin.py:109} INFO - [2022-04-22 10:19:02,663] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/simple_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/simple_dag.py", line 8, in <module>
    description
NameError: name 'description' is not defined
[2022-04-22 10:19:02,680] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/simple_dag.py
[2022-04-22 10:19:02,692] {processor.py:171} INFO - Processing /opt/airflow/dags/simple_dag.py took 0.042 seconds
[2022-04-22 10:19:32,820] {processor.py:163} INFO - Started process (PID=14484) to work on /opt/airflow/dags/simple_dag.py
[2022-04-22 10:19:32,831] {processor.py:642} INFO - Processing file /opt/airflow/dags/simple_dag.py for tasks to queue
[2022-04-22 10:19:32,833] {logging_mixin.py:109} INFO - [2022-04-22 10:19:32,833] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/simple_dag.py
[2022-04-22 10:19:32,842] {logging_mixin.py:109} INFO - [2022-04-22 10:19:32,841] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/simple_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/simple_dag.py", line 8, in <module>
    description
NameError: name 'description' is not defined
[2022-04-22 10:19:32,861] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/simple_dag.py
[2022-04-22 10:19:32,872] {processor.py:171} INFO - Processing /opt/airflow/dags/simple_dag.py took 0.055 seconds
[2022-04-22 10:20:03,010] {processor.py:163} INFO - Started process (PID=14513) to work on /opt/airflow/dags/simple_dag.py
[2022-04-22 10:20:03,019] {processor.py:642} INFO - Processing file /opt/airflow/dags/simple_dag.py for tasks to queue
[2022-04-22 10:20:03,020] {logging_mixin.py:109} INFO - [2022-04-22 10:20:03,020] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/simple_dag.py
[2022-04-22 10:20:03,024] {logging_mixin.py:109} INFO - [2022-04-22 10:20:03,024] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/simple_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/simple_dag.py", line 8, in <module>
    description
NameError: name 'description' is not defined
[2022-04-22 10:20:03,039] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/simple_dag.py
[2022-04-22 10:20:03,048] {processor.py:171} INFO - Processing /opt/airflow/dags/simple_dag.py took 0.042 seconds
[2022-04-22 10:20:33,148] {processor.py:163} INFO - Started process (PID=14533) to work on /opt/airflow/dags/simple_dag.py
[2022-04-22 10:20:33,155] {processor.py:642} INFO - Processing file /opt/airflow/dags/simple_dag.py for tasks to queue
[2022-04-22 10:20:33,156] {logging_mixin.py:109} INFO - [2022-04-22 10:20:33,156] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/simple_dag.py
[2022-04-22 10:20:33,163] {logging_mixin.py:109} INFO - [2022-04-22 10:20:33,162] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/simple_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/simple_dag.py", line 8, in <module>
    description
NameError: name 'description' is not defined
[2022-04-22 10:20:33,179] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/simple_dag.py
[2022-04-22 10:20:33,189] {processor.py:171} INFO - Processing /opt/airflow/dags/simple_dag.py took 0.046 seconds
[2022-04-22 10:21:03,307] {processor.py:163} INFO - Started process (PID=14563) to work on /opt/airflow/dags/simple_dag.py
[2022-04-22 10:21:03,318] {processor.py:642} INFO - Processing file /opt/airflow/dags/simple_dag.py for tasks to queue
[2022-04-22 10:21:03,319] {logging_mixin.py:109} INFO - [2022-04-22 10:21:03,319] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/simple_dag.py
[2022-04-22 10:21:03,335] {logging_mixin.py:109} INFO - [2022-04-22 10:21:03,334] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/simple_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/simple_dag.py", line 8, in <module>
    description
NameError: name 'description' is not defined
[2022-04-22 10:21:03,352] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/simple_dag.py
[2022-04-22 10:21:03,360] {processor.py:171} INFO - Processing /opt/airflow/dags/simple_dag.py took 0.061 seconds
[2022-04-22 10:21:33,407] {processor.py:163} INFO - Started process (PID=14583) to work on /opt/airflow/dags/simple_dag.py
[2022-04-22 10:21:33,417] {processor.py:642} INFO - Processing file /opt/airflow/dags/simple_dag.py for tasks to queue
[2022-04-22 10:21:33,417] {logging_mixin.py:109} INFO - [2022-04-22 10:21:33,417] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/simple_dag.py
[2022-04-22 10:21:33,422] {logging_mixin.py:109} INFO - [2022-04-22 10:21:33,422] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/simple_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/simple_dag.py", line 8, in <module>
    description
NameError: name 'description' is not defined
[2022-04-22 10:21:33,440] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/simple_dag.py
[2022-04-22 10:21:33,449] {processor.py:171} INFO - Processing /opt/airflow/dags/simple_dag.py took 0.045 seconds
[2022-04-22 10:22:03,504] {processor.py:163} INFO - Started process (PID=14615) to work on /opt/airflow/dags/simple_dag.py
[2022-04-22 10:22:03,506] {processor.py:642} INFO - Processing file /opt/airflow/dags/simple_dag.py for tasks to queue
[2022-04-22 10:22:03,507] {logging_mixin.py:109} INFO - [2022-04-22 10:22:03,507] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/simple_dag.py
[2022-04-22 10:22:03,512] {logging_mixin.py:109} INFO - [2022-04-22 10:22:03,511] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/simple_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/simple_dag.py", line 8, in <module>
    description
NameError: name 'description' is not defined
[2022-04-22 10:22:03,529] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/simple_dag.py
[2022-04-22 10:22:03,539] {processor.py:171} INFO - Processing /opt/airflow/dags/simple_dag.py took 0.038 seconds
[2022-04-22 10:22:33,649] {processor.py:163} INFO - Started process (PID=14635) to work on /opt/airflow/dags/simple_dag.py
[2022-04-22 10:22:33,658] {processor.py:642} INFO - Processing file /opt/airflow/dags/simple_dag.py for tasks to queue
[2022-04-22 10:22:33,659] {logging_mixin.py:109} INFO - [2022-04-22 10:22:33,659] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/simple_dag.py
[2022-04-22 10:22:33,665] {logging_mixin.py:109} INFO - [2022-04-22 10:22:33,665] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/simple_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/simple_dag.py", line 8, in <module>
    description
NameError: name 'description' is not defined
[2022-04-22 10:22:33,680] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/simple_dag.py
[2022-04-22 10:22:33,691] {processor.py:171} INFO - Processing /opt/airflow/dags/simple_dag.py took 0.045 seconds
[2022-04-22 10:23:03,807] {processor.py:163} INFO - Started process (PID=14664) to work on /opt/airflow/dags/simple_dag.py
[2022-04-22 10:23:03,817] {processor.py:642} INFO - Processing file /opt/airflow/dags/simple_dag.py for tasks to queue
[2022-04-22 10:23:03,817] {logging_mixin.py:109} INFO - [2022-04-22 10:23:03,817] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/simple_dag.py
[2022-04-22 10:23:03,822] {logging_mixin.py:109} INFO - [2022-04-22 10:23:03,822] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/simple_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/simple_dag.py", line 8, in <module>
    description
NameError: name 'description' is not defined
[2022-04-22 10:23:03,838] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/simple_dag.py
[2022-04-22 10:23:03,846] {processor.py:171} INFO - Processing /opt/airflow/dags/simple_dag.py took 0.042 seconds
[2022-04-22 10:23:33,950] {processor.py:163} INFO - Started process (PID=14684) to work on /opt/airflow/dags/simple_dag.py
[2022-04-22 10:23:33,953] {processor.py:642} INFO - Processing file /opt/airflow/dags/simple_dag.py for tasks to queue
[2022-04-22 10:23:33,955] {logging_mixin.py:109} INFO - [2022-04-22 10:23:33,954] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/simple_dag.py
[2022-04-22 10:23:33,965] {logging_mixin.py:109} INFO - [2022-04-22 10:23:33,964] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/simple_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/simple_dag.py", line 8, in <module>
    description
NameError: name 'description' is not defined
[2022-04-22 10:23:33,992] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/simple_dag.py
[2022-04-22 10:23:34,012] {processor.py:171} INFO - Processing /opt/airflow/dags/simple_dag.py took 0.063 seconds
[2022-04-22 10:24:04,097] {processor.py:163} INFO - Started process (PID=14705) to work on /opt/airflow/dags/simple_dag.py
[2022-04-22 10:24:04,107] {processor.py:642} INFO - Processing file /opt/airflow/dags/simple_dag.py for tasks to queue
[2022-04-22 10:24:04,108] {logging_mixin.py:109} INFO - [2022-04-22 10:24:04,108] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/simple_dag.py
[2022-04-22 10:24:04,115] {logging_mixin.py:109} INFO - [2022-04-22 10:24:04,114] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/simple_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/simple_dag.py", line 8, in <module>
    description
NameError: name 'description' is not defined
[2022-04-22 10:24:04,136] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/simple_dag.py
[2022-04-22 10:24:04,151] {processor.py:171} INFO - Processing /opt/airflow/dags/simple_dag.py took 0.056 seconds
[2022-04-22 10:24:34,208] {processor.py:163} INFO - Started process (PID=14737) to work on /opt/airflow/dags/simple_dag.py
[2022-04-22 10:24:34,217] {processor.py:642} INFO - Processing file /opt/airflow/dags/simple_dag.py for tasks to queue
[2022-04-22 10:24:34,218] {logging_mixin.py:109} INFO - [2022-04-22 10:24:34,218] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/simple_dag.py
[2022-04-22 10:24:34,224] {logging_mixin.py:109} INFO - [2022-04-22 10:24:34,223] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/simple_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/simple_dag.py", line 8, in <module>
    description
NameError: name 'description' is not defined
[2022-04-22 10:24:34,241] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/simple_dag.py
[2022-04-22 10:24:34,250] {processor.py:171} INFO - Processing /opt/airflow/dags/simple_dag.py took 0.045 seconds
[2022-04-22 10:25:04,355] {processor.py:163} INFO - Started process (PID=14758) to work on /opt/airflow/dags/simple_dag.py
[2022-04-22 10:25:04,357] {processor.py:642} INFO - Processing file /opt/airflow/dags/simple_dag.py for tasks to queue
[2022-04-22 10:25:04,357] {logging_mixin.py:109} INFO - [2022-04-22 10:25:04,357] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/simple_dag.py
[2022-04-22 10:25:04,364] {logging_mixin.py:109} INFO - [2022-04-22 10:25:04,363] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/simple_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/simple_dag.py", line 8, in <module>
    description
NameError: name 'description' is not defined
[2022-04-22 10:25:04,383] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/simple_dag.py
[2022-04-22 10:25:04,393] {processor.py:171} INFO - Processing /opt/airflow/dags/simple_dag.py took 0.043 seconds
[2022-04-22 10:25:34,494] {processor.py:163} INFO - Started process (PID=14787) to work on /opt/airflow/dags/simple_dag.py
[2022-04-22 10:25:34,503] {processor.py:642} INFO - Processing file /opt/airflow/dags/simple_dag.py for tasks to queue
[2022-04-22 10:25:34,503] {logging_mixin.py:109} INFO - [2022-04-22 10:25:34,503] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/simple_dag.py
[2022-04-22 10:25:34,508] {logging_mixin.py:109} INFO - [2022-04-22 10:25:34,508] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/simple_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/simple_dag.py", line 8, in <module>
    description
NameError: name 'description' is not defined
[2022-04-22 10:25:34,524] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/simple_dag.py
[2022-04-22 10:25:34,532] {processor.py:171} INFO - Processing /opt/airflow/dags/simple_dag.py took 0.042 seconds
[2022-04-22 10:26:04,659] {processor.py:163} INFO - Started process (PID=14807) to work on /opt/airflow/dags/simple_dag.py
[2022-04-22 10:26:04,668] {processor.py:642} INFO - Processing file /opt/airflow/dags/simple_dag.py for tasks to queue
[2022-04-22 10:26:04,668] {logging_mixin.py:109} INFO - [2022-04-22 10:26:04,668] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/simple_dag.py
[2022-04-22 10:26:04,671] {logging_mixin.py:109} INFO - [2022-04-22 10:26:04,671] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/simple_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/simple_dag.py", line 8, in <module>
    description
NameError: name 'description' is not defined
[2022-04-22 10:26:04,683] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/simple_dag.py
[2022-04-22 10:26:04,690] {processor.py:171} INFO - Processing /opt/airflow/dags/simple_dag.py took 0.033 seconds
[2022-04-22 10:26:34,805] {processor.py:163} INFO - Started process (PID=14839) to work on /opt/airflow/dags/simple_dag.py
[2022-04-22 10:26:34,806] {processor.py:642} INFO - Processing file /opt/airflow/dags/simple_dag.py for tasks to queue
[2022-04-22 10:26:34,807] {logging_mixin.py:109} INFO - [2022-04-22 10:26:34,806] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/simple_dag.py
[2022-04-22 10:26:34,814] {logging_mixin.py:109} INFO - [2022-04-22 10:26:34,813] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/simple_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/simple_dag.py", line 8, in <module>
    description
NameError: name 'description' is not defined
[2022-04-22 10:26:34,831] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/simple_dag.py
[2022-04-22 10:26:34,841] {processor.py:171} INFO - Processing /opt/airflow/dags/simple_dag.py took 0.040 seconds
[2022-04-22 10:27:04,943] {processor.py:163} INFO - Started process (PID=14860) to work on /opt/airflow/dags/simple_dag.py
[2022-04-22 10:27:04,944] {processor.py:642} INFO - Processing file /opt/airflow/dags/simple_dag.py for tasks to queue
[2022-04-22 10:27:04,944] {logging_mixin.py:109} INFO - [2022-04-22 10:27:04,944] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/simple_dag.py
[2022-04-22 10:27:04,949] {logging_mixin.py:109} INFO - [2022-04-22 10:27:04,949] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/simple_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/simple_dag.py", line 8, in <module>
    description
NameError: name 'description' is not defined
[2022-04-22 10:27:04,965] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/simple_dag.py
[2022-04-22 10:27:04,973] {processor.py:171} INFO - Processing /opt/airflow/dags/simple_dag.py took 0.034 seconds
[2022-04-22 10:27:35,080] {processor.py:163} INFO - Started process (PID=14889) to work on /opt/airflow/dags/simple_dag.py
[2022-04-22 10:27:35,089] {processor.py:642} INFO - Processing file /opt/airflow/dags/simple_dag.py for tasks to queue
[2022-04-22 10:27:35,090] {logging_mixin.py:109} INFO - [2022-04-22 10:27:35,090] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/simple_dag.py
[2022-04-22 10:27:35,097] {logging_mixin.py:109} INFO - [2022-04-22 10:27:35,096] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/simple_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/simple_dag.py", line 8, in <module>
    description
NameError: name 'description' is not defined
[2022-04-22 10:27:35,113] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/simple_dag.py
[2022-04-22 10:27:35,123] {processor.py:171} INFO - Processing /opt/airflow/dags/simple_dag.py took 0.046 seconds
[2022-04-22 10:28:05,214] {processor.py:163} INFO - Started process (PID=14909) to work on /opt/airflow/dags/simple_dag.py
[2022-04-22 10:28:05,224] {processor.py:642} INFO - Processing file /opt/airflow/dags/simple_dag.py for tasks to queue
[2022-04-22 10:28:05,224] {logging_mixin.py:109} INFO - [2022-04-22 10:28:05,224] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/simple_dag.py
[2022-04-22 10:28:05,230] {logging_mixin.py:109} INFO - [2022-04-22 10:28:05,229] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/simple_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/simple_dag.py", line 8, in <module>
    description
NameError: name 'description' is not defined
[2022-04-22 10:28:05,246] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/simple_dag.py
[2022-04-22 10:28:05,255] {processor.py:171} INFO - Processing /opt/airflow/dags/simple_dag.py took 0.043 seconds
[2022-04-22 10:28:35,356] {processor.py:163} INFO - Started process (PID=14938) to work on /opt/airflow/dags/simple_dag.py
[2022-04-22 10:28:35,365] {processor.py:642} INFO - Processing file /opt/airflow/dags/simple_dag.py for tasks to queue
[2022-04-22 10:28:35,365] {logging_mixin.py:109} INFO - [2022-04-22 10:28:35,365] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/simple_dag.py
[2022-04-22 10:28:35,371] {logging_mixin.py:109} INFO - [2022-04-22 10:28:35,370] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/simple_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/simple_dag.py", line 8, in <module>
    description
NameError: name 'description' is not defined
[2022-04-22 10:28:35,384] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/simple_dag.py
[2022-04-22 10:28:35,392] {processor.py:171} INFO - Processing /opt/airflow/dags/simple_dag.py took 0.038 seconds
[2022-04-22 10:29:05,502] {processor.py:163} INFO - Started process (PID=14958) to work on /opt/airflow/dags/simple_dag.py
[2022-04-22 10:29:05,512] {processor.py:642} INFO - Processing file /opt/airflow/dags/simple_dag.py for tasks to queue
[2022-04-22 10:29:05,512] {logging_mixin.py:109} INFO - [2022-04-22 10:29:05,512] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/simple_dag.py
[2022-04-22 10:29:05,518] {logging_mixin.py:109} INFO - [2022-04-22 10:29:05,517] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/simple_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/simple_dag.py", line 8, in <module>
    description
NameError: name 'description' is not defined
[2022-04-22 10:29:05,531] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/simple_dag.py
[2022-04-22 10:29:05,541] {processor.py:171} INFO - Processing /opt/airflow/dags/simple_dag.py took 0.041 seconds
[2022-04-22 10:29:35,638] {processor.py:163} INFO - Started process (PID=14989) to work on /opt/airflow/dags/simple_dag.py
[2022-04-22 10:29:35,648] {processor.py:642} INFO - Processing file /opt/airflow/dags/simple_dag.py for tasks to queue
[2022-04-22 10:29:35,648] {logging_mixin.py:109} INFO - [2022-04-22 10:29:35,648] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/simple_dag.py
[2022-04-22 10:29:35,653] {logging_mixin.py:109} INFO - [2022-04-22 10:29:35,652] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/simple_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/simple_dag.py", line 8, in <module>
    description
NameError: name 'description' is not defined
[2022-04-22 10:29:35,668] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/simple_dag.py
[2022-04-22 10:29:35,675] {processor.py:171} INFO - Processing /opt/airflow/dags/simple_dag.py took 0.040 seconds
[2022-04-22 10:30:05,780] {processor.py:163} INFO - Started process (PID=15010) to work on /opt/airflow/dags/simple_dag.py
[2022-04-22 10:30:05,781] {processor.py:642} INFO - Processing file /opt/airflow/dags/simple_dag.py for tasks to queue
[2022-04-22 10:30:05,781] {logging_mixin.py:109} INFO - [2022-04-22 10:30:05,781] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/simple_dag.py
[2022-04-22 10:30:05,788] {logging_mixin.py:109} INFO - [2022-04-22 10:30:05,787] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/simple_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/simple_dag.py", line 8, in <module>
    description
NameError: name 'description' is not defined
[2022-04-22 10:30:05,808] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/simple_dag.py
[2022-04-22 10:30:05,819] {processor.py:171} INFO - Processing /opt/airflow/dags/simple_dag.py took 0.042 seconds
[2022-04-22 10:30:35,938] {processor.py:163} INFO - Started process (PID=15039) to work on /opt/airflow/dags/simple_dag.py
[2022-04-22 10:30:35,939] {processor.py:642} INFO - Processing file /opt/airflow/dags/simple_dag.py for tasks to queue
[2022-04-22 10:30:35,940] {logging_mixin.py:109} INFO - [2022-04-22 10:30:35,940] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/simple_dag.py
[2022-04-22 10:30:35,947] {logging_mixin.py:109} INFO - [2022-04-22 10:30:35,946] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/simple_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/simple_dag.py", line 8, in <module>
    description
NameError: name 'description' is not defined
[2022-04-22 10:30:35,963] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/simple_dag.py
[2022-04-22 10:30:35,974] {processor.py:171} INFO - Processing /opt/airflow/dags/simple_dag.py took 0.040 seconds
[2022-04-22 10:31:06,069] {processor.py:163} INFO - Started process (PID=15059) to work on /opt/airflow/dags/simple_dag.py
[2022-04-22 10:31:06,078] {processor.py:642} INFO - Processing file /opt/airflow/dags/simple_dag.py for tasks to queue
[2022-04-22 10:31:06,079] {logging_mixin.py:109} INFO - [2022-04-22 10:31:06,079] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/simple_dag.py
[2022-04-22 10:31:06,084] {logging_mixin.py:109} INFO - [2022-04-22 10:31:06,083] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/simple_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/simple_dag.py", line 8, in <module>
    description
NameError: name 'description' is not defined
[2022-04-22 10:31:06,100] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/simple_dag.py
[2022-04-22 10:31:06,109] {processor.py:171} INFO - Processing /opt/airflow/dags/simple_dag.py took 0.043 seconds
[2022-04-22 10:31:36,209] {processor.py:163} INFO - Started process (PID=15089) to work on /opt/airflow/dags/simple_dag.py
[2022-04-22 10:31:36,211] {processor.py:642} INFO - Processing file /opt/airflow/dags/simple_dag.py for tasks to queue
[2022-04-22 10:31:36,212] {logging_mixin.py:109} INFO - [2022-04-22 10:31:36,212] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/simple_dag.py
[2022-04-22 10:31:36,225] {logging_mixin.py:109} INFO - [2022-04-22 10:31:36,223] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/simple_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/simple_dag.py", line 8, in <module>
    description
NameError: name 'description' is not defined
[2022-04-22 10:31:36,251] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/simple_dag.py
[2022-04-22 10:31:36,271] {processor.py:171} INFO - Processing /opt/airflow/dags/simple_dag.py took 0.066 seconds
[2022-04-22 10:32:06,338] {processor.py:163} INFO - Started process (PID=15110) to work on /opt/airflow/dags/simple_dag.py
[2022-04-22 10:32:06,340] {processor.py:642} INFO - Processing file /opt/airflow/dags/simple_dag.py for tasks to queue
[2022-04-22 10:32:06,341] {logging_mixin.py:109} INFO - [2022-04-22 10:32:06,341] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/simple_dag.py
[2022-04-22 10:32:06,347] {logging_mixin.py:109} INFO - [2022-04-22 10:32:06,346] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/simple_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/simple_dag.py", line 8, in <module>
    description
NameError: name 'description' is not defined
[2022-04-22 10:32:06,369] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/simple_dag.py
[2022-04-22 10:32:06,385] {processor.py:171} INFO - Processing /opt/airflow/dags/simple_dag.py took 0.050 seconds
[2022-04-22 10:32:36,455] {processor.py:163} INFO - Started process (PID=15130) to work on /opt/airflow/dags/simple_dag.py
[2022-04-22 10:32:36,464] {processor.py:642} INFO - Processing file /opt/airflow/dags/simple_dag.py for tasks to queue
[2022-04-22 10:32:36,465] {logging_mixin.py:109} INFO - [2022-04-22 10:32:36,465] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/simple_dag.py
[2022-04-22 10:32:36,472] {logging_mixin.py:109} INFO - [2022-04-22 10:32:36,471] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/simple_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/simple_dag.py", line 8, in <module>
    description
NameError: name 'description' is not defined
[2022-04-22 10:32:36,488] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/simple_dag.py
[2022-04-22 10:32:36,496] {processor.py:171} INFO - Processing /opt/airflow/dags/simple_dag.py took 0.048 seconds
[2022-04-22 10:33:06,582] {processor.py:163} INFO - Started process (PID=15160) to work on /opt/airflow/dags/simple_dag.py
[2022-04-22 10:33:06,591] {processor.py:642} INFO - Processing file /opt/airflow/dags/simple_dag.py for tasks to queue
[2022-04-22 10:33:06,591] {logging_mixin.py:109} INFO - [2022-04-22 10:33:06,591] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/simple_dag.py
[2022-04-22 10:33:06,596] {logging_mixin.py:109} INFO - [2022-04-22 10:33:06,595] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/simple_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/simple_dag.py", line 8, in <module>
    description
NameError: name 'description' is not defined
[2022-04-22 10:33:06,608] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/simple_dag.py
[2022-04-22 10:33:06,615] {processor.py:171} INFO - Processing /opt/airflow/dags/simple_dag.py took 0.035 seconds
[2022-04-22 10:33:36,708] {processor.py:163} INFO - Started process (PID=15181) to work on /opt/airflow/dags/simple_dag.py
[2022-04-22 10:33:36,709] {processor.py:642} INFO - Processing file /opt/airflow/dags/simple_dag.py for tasks to queue
[2022-04-22 10:33:36,709] {logging_mixin.py:109} INFO - [2022-04-22 10:33:36,709] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/simple_dag.py
[2022-04-22 10:33:36,713] {logging_mixin.py:109} INFO - [2022-04-22 10:33:36,713] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/simple_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/simple_dag.py", line 8, in <module>
    description
NameError: name 'description' is not defined
[2022-04-22 10:33:36,725] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/simple_dag.py
[2022-04-22 10:33:36,732] {processor.py:171} INFO - Processing /opt/airflow/dags/simple_dag.py took 0.027 seconds
[2022-04-22 10:34:06,851] {processor.py:163} INFO - Started process (PID=15210) to work on /opt/airflow/dags/simple_dag.py
[2022-04-22 10:34:06,863] {processor.py:642} INFO - Processing file /opt/airflow/dags/simple_dag.py for tasks to queue
[2022-04-22 10:34:06,865] {logging_mixin.py:109} INFO - [2022-04-22 10:34:06,865] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/simple_dag.py
[2022-04-22 10:34:06,875] {logging_mixin.py:109} INFO - [2022-04-22 10:34:06,874] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/simple_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/simple_dag.py", line 8, in <module>
    description
NameError: name 'description' is not defined
[2022-04-22 10:34:06,889] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/simple_dag.py
[2022-04-22 10:34:06,897] {processor.py:171} INFO - Processing /opt/airflow/dags/simple_dag.py took 0.054 seconds
[2022-04-22 10:34:36,944] {processor.py:163} INFO - Started process (PID=15230) to work on /opt/airflow/dags/simple_dag.py
[2022-04-22 10:34:36,945] {processor.py:642} INFO - Processing file /opt/airflow/dags/simple_dag.py for tasks to queue
[2022-04-22 10:34:36,945] {logging_mixin.py:109} INFO - [2022-04-22 10:34:36,945] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/simple_dag.py
[2022-04-22 10:34:36,952] {logging_mixin.py:109} INFO - [2022-04-22 10:34:36,951] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/simple_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/simple_dag.py", line 8, in <module>
    description
NameError: name 'description' is not defined
[2022-04-22 10:34:36,969] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/simple_dag.py
[2022-04-22 10:34:36,982] {processor.py:171} INFO - Processing /opt/airflow/dags/simple_dag.py took 0.041 seconds
[2022-04-22 10:35:07,090] {processor.py:163} INFO - Started process (PID=15259) to work on /opt/airflow/dags/simple_dag.py
[2022-04-22 10:35:07,099] {processor.py:642} INFO - Processing file /opt/airflow/dags/simple_dag.py for tasks to queue
[2022-04-22 10:35:07,099] {logging_mixin.py:109} INFO - [2022-04-22 10:35:07,099] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/simple_dag.py
[2022-04-22 10:35:07,103] {logging_mixin.py:109} INFO - [2022-04-22 10:35:07,102] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/simple_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/simple_dag.py", line 8, in <module>
    description
NameError: name 'description' is not defined
[2022-04-22 10:35:07,115] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/simple_dag.py
[2022-04-22 10:35:07,122] {processor.py:171} INFO - Processing /opt/airflow/dags/simple_dag.py took 0.035 seconds
[2022-04-22 10:35:37,229] {processor.py:163} INFO - Started process (PID=15280) to work on /opt/airflow/dags/simple_dag.py
[2022-04-22 10:35:37,231] {processor.py:642} INFO - Processing file /opt/airflow/dags/simple_dag.py for tasks to queue
[2022-04-22 10:35:37,231] {logging_mixin.py:109} INFO - [2022-04-22 10:35:37,231] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/simple_dag.py
[2022-04-22 10:35:37,235] {logging_mixin.py:109} INFO - [2022-04-22 10:35:37,235] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/simple_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/simple_dag.py", line 8, in <module>
    description
NameError: name 'description' is not defined
[2022-04-22 10:35:37,247] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/simple_dag.py
[2022-04-22 10:35:37,254] {processor.py:171} INFO - Processing /opt/airflow/dags/simple_dag.py took 0.027 seconds
[2022-04-22 10:36:07,354] {processor.py:163} INFO - Started process (PID=15310) to work on /opt/airflow/dags/simple_dag.py
[2022-04-22 10:36:07,354] {processor.py:642} INFO - Processing file /opt/airflow/dags/simple_dag.py for tasks to queue
[2022-04-22 10:36:07,355] {logging_mixin.py:109} INFO - [2022-04-22 10:36:07,355] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/simple_dag.py
[2022-04-22 10:36:07,361] {logging_mixin.py:109} INFO - [2022-04-22 10:36:07,360] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/simple_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/simple_dag.py", line 8, in <module>
    description
NameError: name 'description' is not defined
[2022-04-22 10:36:07,374] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/simple_dag.py
[2022-04-22 10:36:07,382] {processor.py:171} INFO - Processing /opt/airflow/dags/simple_dag.py took 0.030 seconds
[2022-04-22 10:36:37,510] {processor.py:163} INFO - Started process (PID=15330) to work on /opt/airflow/dags/simple_dag.py
[2022-04-22 10:36:37,519] {processor.py:642} INFO - Processing file /opt/airflow/dags/simple_dag.py for tasks to queue
[2022-04-22 10:36:37,520] {logging_mixin.py:109} INFO - [2022-04-22 10:36:37,520] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/simple_dag.py
[2022-04-22 10:36:37,524] {logging_mixin.py:109} INFO - [2022-04-22 10:36:37,524] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/simple_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/simple_dag.py", line 8, in <module>
    description
NameError: name 'description' is not defined
[2022-04-22 10:36:37,539] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/simple_dag.py
[2022-04-22 10:36:37,546] {processor.py:171} INFO - Processing /opt/airflow/dags/simple_dag.py took 0.039 seconds
[2022-04-22 10:37:07,668] {processor.py:163} INFO - Started process (PID=15359) to work on /opt/airflow/dags/simple_dag.py
[2022-04-22 10:37:07,678] {processor.py:642} INFO - Processing file /opt/airflow/dags/simple_dag.py for tasks to queue
[2022-04-22 10:37:07,678] {logging_mixin.py:109} INFO - [2022-04-22 10:37:07,678] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/simple_dag.py
[2022-04-22 10:37:07,683] {logging_mixin.py:109} INFO - [2022-04-22 10:37:07,683] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/simple_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/simple_dag.py", line 8, in <module>
    description
NameError: name 'description' is not defined
[2022-04-22 10:37:07,697] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/simple_dag.py
[2022-04-22 10:37:07,710] {processor.py:171} INFO - Processing /opt/airflow/dags/simple_dag.py took 0.044 seconds
[2022-04-22 10:37:37,791] {processor.py:163} INFO - Started process (PID=15379) to work on /opt/airflow/dags/simple_dag.py
[2022-04-22 10:37:37,801] {processor.py:642} INFO - Processing file /opt/airflow/dags/simple_dag.py for tasks to queue
[2022-04-22 10:37:37,801] {logging_mixin.py:109} INFO - [2022-04-22 10:37:37,801] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/simple_dag.py
[2022-04-22 10:37:37,806] {logging_mixin.py:109} INFO - [2022-04-22 10:37:37,805] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/simple_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/simple_dag.py", line 8, in <module>
    description
NameError: name 'description' is not defined
[2022-04-22 10:37:37,839] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/simple_dag.py
[2022-04-22 10:37:37,846] {processor.py:171} INFO - Processing /opt/airflow/dags/simple_dag.py took 0.058 seconds
