[2022-05-04 13:59:54,571] {processor.py:163} INFO - Started process (PID=48) to work on /opt/airflow/dags/dummydag.py
[2022-05-04 13:59:54,572] {processor.py:642} INFO - Processing file /opt/airflow/dags/dummydag.py for tasks to queue
[2022-05-04 13:59:54,573] {logging_mixin.py:109} INFO - [2022-05-04 13:59:54,573] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/dummydag.py
[2022-05-04 13:59:54,576] {logging_mixin.py:109} INFO - [2022-05-04 13:59:54,575] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/dummydag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dummydag.py", line 12
    start_date=datetime(2021,1,1)
             ^
SyntaxError: invalid syntax
[2022-05-04 13:59:54,631] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/dummydag.py
[2022-05-04 13:59:54,663] {processor.py:171} INFO - Processing /opt/airflow/dags/dummydag.py took 0.097 seconds
[2022-05-04 14:00:24,790] {processor.py:163} INFO - Started process (PID=69) to work on /opt/airflow/dags/dummydag.py
[2022-05-04 14:00:24,791] {processor.py:642} INFO - Processing file /opt/airflow/dags/dummydag.py for tasks to queue
[2022-05-04 14:00:24,791] {logging_mixin.py:109} INFO - [2022-05-04 14:00:24,791] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/dummydag.py
[2022-05-04 14:00:24,799] {logging_mixin.py:109} INFO - [2022-05-04 14:00:24,798] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/dummydag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dummydag.py", line 12
    start_date=datetime(2021,1,1)
             ^
SyntaxError: invalid syntax
[2022-05-04 14:00:24,811] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/dummydag.py
[2022-05-04 14:00:24,818] {processor.py:171} INFO - Processing /opt/airflow/dags/dummydag.py took 0.030 seconds
[2022-05-04 14:00:54,935] {processor.py:163} INFO - Started process (PID=108) to work on /opt/airflow/dags/dummydag.py
[2022-05-04 14:00:54,936] {processor.py:642} INFO - Processing file /opt/airflow/dags/dummydag.py for tasks to queue
[2022-05-04 14:00:54,936] {logging_mixin.py:109} INFO - [2022-05-04 14:00:54,936] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/dummydag.py
[2022-05-04 14:00:54,938] {logging_mixin.py:109} INFO - [2022-05-04 14:00:54,937] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/dummydag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dummydag.py", line 12
    start_date=datetime(2021,1,1)
             ^
SyntaxError: invalid syntax
[2022-05-04 14:00:54,951] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/dummydag.py
[2022-05-04 14:00:54,959] {processor.py:171} INFO - Processing /opt/airflow/dags/dummydag.py took 0.026 seconds
[2022-05-04 14:01:25,085] {processor.py:163} INFO - Started process (PID=137) to work on /opt/airflow/dags/dummydag.py
[2022-05-04 14:01:25,090] {processor.py:642} INFO - Processing file /opt/airflow/dags/dummydag.py for tasks to queue
[2022-05-04 14:01:25,091] {logging_mixin.py:109} INFO - [2022-05-04 14:01:25,091] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/dummydag.py
[2022-05-04 14:01:25,092] {logging_mixin.py:109} INFO - [2022-05-04 14:01:25,091] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/dummydag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dummydag.py", line 12
    start_date=datetime(2021,1,1)
             ^
SyntaxError: invalid syntax
[2022-05-04 14:01:25,103] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/dummydag.py
[2022-05-04 14:01:25,110] {processor.py:171} INFO - Processing /opt/airflow/dags/dummydag.py took 0.026 seconds
[2022-05-04 14:01:55,221] {processor.py:163} INFO - Started process (PID=175) to work on /opt/airflow/dags/dummydag.py
[2022-05-04 14:01:55,228] {processor.py:642} INFO - Processing file /opt/airflow/dags/dummydag.py for tasks to queue
[2022-05-04 14:01:55,228] {logging_mixin.py:109} INFO - [2022-05-04 14:01:55,228] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/dummydag.py
[2022-05-04 14:01:55,230] {logging_mixin.py:109} INFO - [2022-05-04 14:01:55,229] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/dummydag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dummydag.py", line 12
    start_date=datetime(2021,1,1)
             ^
SyntaxError: invalid syntax
[2022-05-04 14:01:55,243] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/dummydag.py
[2022-05-04 14:01:55,253] {processor.py:171} INFO - Processing /opt/airflow/dags/dummydag.py took 0.033 seconds
[2022-05-04 14:02:25,393] {processor.py:163} INFO - Started process (PID=205) to work on /opt/airflow/dags/dummydag.py
[2022-05-04 14:02:25,395] {processor.py:642} INFO - Processing file /opt/airflow/dags/dummydag.py for tasks to queue
[2022-05-04 14:02:25,395] {logging_mixin.py:109} INFO - [2022-05-04 14:02:25,395] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/dummydag.py
[2022-05-04 14:02:25,398] {logging_mixin.py:109} INFO - [2022-05-04 14:02:25,397] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/dummydag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dummydag.py", line 12
    start_date=datetime(2021,1,1)
             ^
SyntaxError: invalid syntax
[2022-05-04 14:02:25,421] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/dummydag.py
[2022-05-04 14:02:25,432] {processor.py:171} INFO - Processing /opt/airflow/dags/dummydag.py took 0.043 seconds
[2022-05-04 14:02:55,556] {processor.py:163} INFO - Started process (PID=245) to work on /opt/airflow/dags/dummydag.py
[2022-05-04 14:02:55,562] {processor.py:642} INFO - Processing file /opt/airflow/dags/dummydag.py for tasks to queue
[2022-05-04 14:02:55,563] {logging_mixin.py:109} INFO - [2022-05-04 14:02:55,562] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/dummydag.py
[2022-05-04 14:02:55,564] {logging_mixin.py:109} INFO - [2022-05-04 14:02:55,563] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/dummydag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dummydag.py", line 12
    start_date=datetime(2021,1,1)
             ^
SyntaxError: invalid syntax
[2022-05-04 14:02:55,578] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/dummydag.py
[2022-05-04 14:02:55,585] {processor.py:171} INFO - Processing /opt/airflow/dags/dummydag.py took 0.032 seconds
[2022-05-04 14:03:25,724] {processor.py:163} INFO - Started process (PID=274) to work on /opt/airflow/dags/dummydag.py
[2022-05-04 14:03:25,730] {processor.py:642} INFO - Processing file /opt/airflow/dags/dummydag.py for tasks to queue
[2022-05-04 14:03:25,730] {logging_mixin.py:109} INFO - [2022-05-04 14:03:25,730] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/dummydag.py
[2022-05-04 14:03:25,732] {logging_mixin.py:109} INFO - [2022-05-04 14:03:25,731] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/dummydag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dummydag.py", line 12
    start_date=datetime(2021,1,1)
             ^
SyntaxError: invalid syntax
[2022-05-04 14:03:25,748] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/dummydag.py
[2022-05-04 14:03:25,759] {processor.py:171} INFO - Processing /opt/airflow/dags/dummydag.py took 0.038 seconds
[2022-05-04 14:03:55,897] {processor.py:163} INFO - Started process (PID=313) to work on /opt/airflow/dags/dummydag.py
[2022-05-04 14:03:55,904] {processor.py:642} INFO - Processing file /opt/airflow/dags/dummydag.py for tasks to queue
[2022-05-04 14:03:55,904] {logging_mixin.py:109} INFO - [2022-05-04 14:03:55,904] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/dummydag.py
[2022-05-04 14:03:55,906] {logging_mixin.py:109} INFO - [2022-05-04 14:03:55,905] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/dummydag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dummydag.py", line 12
    start_date=datetime(2021,1,1)
             ^
SyntaxError: invalid syntax
[2022-05-04 14:03:55,920] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/dummydag.py
[2022-05-04 14:03:55,933] {processor.py:171} INFO - Processing /opt/airflow/dags/dummydag.py took 0.038 seconds
[2022-05-04 14:04:26,117] {processor.py:163} INFO - Started process (PID=342) to work on /opt/airflow/dags/dummydag.py
[2022-05-04 14:04:26,123] {processor.py:642} INFO - Processing file /opt/airflow/dags/dummydag.py for tasks to queue
[2022-05-04 14:04:26,124] {logging_mixin.py:109} INFO - [2022-05-04 14:04:26,124] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/dummydag.py
[2022-05-04 14:04:26,125] {logging_mixin.py:109} INFO - [2022-05-04 14:04:26,125] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/dummydag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dummydag.py", line 12
    start_date=datetime(2021,1,1)
             ^
SyntaxError: invalid syntax
[2022-05-04 14:04:26,139] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/dummydag.py
[2022-05-04 14:04:26,148] {processor.py:171} INFO - Processing /opt/airflow/dags/dummydag.py took 0.034 seconds
[2022-05-04 14:04:56,286] {processor.py:163} INFO - Started process (PID=380) to work on /opt/airflow/dags/dummydag.py
[2022-05-04 14:04:56,291] {processor.py:642} INFO - Processing file /opt/airflow/dags/dummydag.py for tasks to queue
[2022-05-04 14:04:56,291] {logging_mixin.py:109} INFO - [2022-05-04 14:04:56,291] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/dummydag.py
[2022-05-04 14:04:56,294] {logging_mixin.py:109} INFO - [2022-05-04 14:04:56,292] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/dummydag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dummydag.py", line 12
    start_date=datetime(2021,1,1)
             ^
SyntaxError: invalid syntax
[2022-05-04 14:04:56,310] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/dummydag.py
[2022-05-04 14:04:56,322] {processor.py:171} INFO - Processing /opt/airflow/dags/dummydag.py took 0.039 seconds
[2022-05-04 14:05:26,448] {processor.py:163} INFO - Started process (PID=410) to work on /opt/airflow/dags/dummydag.py
[2022-05-04 14:05:26,454] {processor.py:642} INFO - Processing file /opt/airflow/dags/dummydag.py for tasks to queue
[2022-05-04 14:05:26,455] {logging_mixin.py:109} INFO - [2022-05-04 14:05:26,455] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/dummydag.py
[2022-05-04 14:05:26,456] {logging_mixin.py:109} INFO - [2022-05-04 14:05:26,455] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/dummydag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dummydag.py", line 12
    start_date=datetime(2021,1,1)
             ^
SyntaxError: invalid syntax
[2022-05-04 14:05:26,469] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/dummydag.py
[2022-05-04 14:05:26,476] {processor.py:171} INFO - Processing /opt/airflow/dags/dummydag.py took 0.030 seconds
[2022-05-04 14:05:56,614] {processor.py:163} INFO - Started process (PID=449) to work on /opt/airflow/dags/dummydag.py
[2022-05-04 14:05:56,619] {processor.py:642} INFO - Processing file /opt/airflow/dags/dummydag.py for tasks to queue
[2022-05-04 14:05:56,619] {logging_mixin.py:109} INFO - [2022-05-04 14:05:56,619] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/dummydag.py
[2022-05-04 14:05:56,622] {logging_mixin.py:109} INFO - [2022-05-04 14:05:56,621] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/dummydag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dummydag.py", line 12
    start_date=datetime(2021,1,1)
             ^
SyntaxError: invalid syntax
[2022-05-04 14:05:56,642] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/dummydag.py
[2022-05-04 14:05:56,652] {processor.py:171} INFO - Processing /opt/airflow/dags/dummydag.py took 0.042 seconds
[2022-05-04 14:06:26,815] {processor.py:163} INFO - Started process (PID=478) to work on /opt/airflow/dags/dummydag.py
[2022-05-04 14:06:26,821] {processor.py:642} INFO - Processing file /opt/airflow/dags/dummydag.py for tasks to queue
[2022-05-04 14:06:26,821] {logging_mixin.py:109} INFO - [2022-05-04 14:06:26,821] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/dummydag.py
[2022-05-04 14:06:26,823] {logging_mixin.py:109} INFO - [2022-05-04 14:06:26,823] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/dummydag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dummydag.py", line 12
    start_date=datetime(2021,1,1)
             ^
SyntaxError: invalid syntax
[2022-05-04 14:06:26,838] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/dummydag.py
[2022-05-04 14:06:26,847] {processor.py:171} INFO - Processing /opt/airflow/dags/dummydag.py took 0.035 seconds
[2022-05-04 14:06:56,877] {processor.py:163} INFO - Started process (PID=515) to work on /opt/airflow/dags/dummydag.py
[2022-05-04 14:06:56,888] {processor.py:642} INFO - Processing file /opt/airflow/dags/dummydag.py for tasks to queue
[2022-05-04 14:06:56,890] {logging_mixin.py:109} INFO - [2022-05-04 14:06:56,889] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/dummydag.py
[2022-05-04 14:06:56,892] {logging_mixin.py:109} INFO - [2022-05-04 14:06:56,892] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/dummydag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dummydag.py", line 12
    start_date=datetime(2021,1,1)
             ^
SyntaxError: invalid syntax
[2022-05-04 14:06:56,910] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/dummydag.py
[2022-05-04 14:06:56,923] {processor.py:171} INFO - Processing /opt/airflow/dags/dummydag.py took 0.049 seconds
[2022-05-04 14:07:27,114] {processor.py:163} INFO - Started process (PID=545) to work on /opt/airflow/dags/dummydag.py
[2022-05-04 14:07:27,121] {processor.py:642} INFO - Processing file /opt/airflow/dags/dummydag.py for tasks to queue
[2022-05-04 14:07:27,121] {logging_mixin.py:109} INFO - [2022-05-04 14:07:27,121] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/dummydag.py
[2022-05-04 14:07:27,122] {logging_mixin.py:109} INFO - [2022-05-04 14:07:27,122] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/dummydag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dummydag.py", line 12
    start_date=datetime(2021,1,1)
             ^
SyntaxError: invalid syntax
[2022-05-04 14:07:27,136] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/dummydag.py
[2022-05-04 14:07:27,143] {processor.py:171} INFO - Processing /opt/airflow/dags/dummydag.py took 0.030 seconds
[2022-05-04 14:07:57,201] {processor.py:163} INFO - Started process (PID=583) to work on /opt/airflow/dags/dummydag.py
[2022-05-04 14:07:57,208] {processor.py:642} INFO - Processing file /opt/airflow/dags/dummydag.py for tasks to queue
[2022-05-04 14:07:57,208] {logging_mixin.py:109} INFO - [2022-05-04 14:07:57,208] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/dummydag.py
[2022-05-04 14:07:57,209] {logging_mixin.py:109} INFO - [2022-05-04 14:07:57,209] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/dummydag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dummydag.py", line 12
    start_date=datetime(2021,1,1)
             ^
SyntaxError: invalid syntax
[2022-05-04 14:07:57,221] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/dummydag.py
[2022-05-04 14:07:57,228] {processor.py:171} INFO - Processing /opt/airflow/dags/dummydag.py took 0.029 seconds
[2022-05-04 14:08:27,373] {processor.py:163} INFO - Started process (PID=613) to work on /opt/airflow/dags/dummydag.py
[2022-05-04 14:08:27,374] {processor.py:642} INFO - Processing file /opt/airflow/dags/dummydag.py for tasks to queue
[2022-05-04 14:08:27,375] {logging_mixin.py:109} INFO - [2022-05-04 14:08:27,375] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/dummydag.py
[2022-05-04 14:08:27,377] {logging_mixin.py:109} INFO - [2022-05-04 14:08:27,376] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/dummydag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dummydag.py", line 12
    start_date=datetime(2021,1,1)
             ^
SyntaxError: invalid syntax
[2022-05-04 14:08:27,395] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/dummydag.py
[2022-05-04 14:08:27,408] {processor.py:171} INFO - Processing /opt/airflow/dags/dummydag.py took 0.038 seconds
